### PR TITLE
Pass request by name into methods

### PR DESCRIPTION
**Pull request by gadomski**
**Related Issue(s):**

- This makes #22 less breaking.

**Description:**

Some downstreams, e.g. the Planetary Computer, use the `request` as a part of their caching mechanism. #22 has some internal calls to functions where `request` is passed as a positional parameter, which breaks generic caching mechanism, which fetch `request` from `kwargs`. This PR changes to make sure those internal calls pass `request` by name.

**PR Checklist:**

- [x] `pre-commit` hooks pass locally
- [x] Tests pass (run `make test`)
- [ ] Documentation has been updated to reflect changes, if applicable, and docs build successfully (run `make docs`)
- [x] Changes are added to the [CHANGELOG](https://github.com/stac-utils/stac-fastapi/blob/main/CHANGES.md).

### CODE REVIEW

**Review by mmcfarland — APPROVED** [review]

**Review by pjhartzell — COMMENTED** [review]
Are we concerned about regression? Or do we trust future devs to inspect the history and understand that there is a reason (untested) for these positional args to be passed as keyword args?

**Comment by gadomski** [comment]
> Are we concerned about regression? Or do we trust future devs to inspect the history and understand that there is a reason (untested) for these positional args to be passed as keyword args?

It's a good point. We _could_ sprinkle comments around explaining what's going on, but that feels like a bit of a rabbit hole. I think it's ok to just have the explanation in the git/github history.

**Comment by pjhartzell** [comment]
Would a test be overkill? A regression would fail the test, which would make clear that those args are keyword-ed for a reason.

**Comment by gadomski** [comment]
No a test makes sense, I'll add something that mimics what the PC is doing.

**Comment by gadomski** [comment]
Whelp, that test ended up being more involved than expected, but got it.

**Review by pjhartzell — APPROVED** [review]

**Pull request merged**
