### PR TITLE
Release v2.4.11

### PR DESCRIPTION
**Pull request by edkeeble**
**Description:**

**PR Checklist:**

- [x] `pre-commit` hooks pass locally
- [x] Tests pass (run `make test`)
- [x] Documentation has been updated to reflect changes, if applicable, and docs build successfully (run `make docs`)
- [x] Changes are added to the [CHANGELOG](https://github.com/stac-utils/stac-fastapi/blob/main/CHANGES.md).

### CODE REVIEW

**Comment by gadomski** [comment]
Sorry for the delay on this @edkeeble, tests are currently failing locally for me on **main** (and in other simple PRs, e.g. https://github.com/stac-utils/stac-fastapi-pgstac/pull/69) so I'd like to sort that out before cutting a release.

**Comment by edkeeble** [comment]
@gadomski no problem. That's curious. Tests are still passing locally for me on main. Happy to help debug, if it's useful.

Somewhat related, but probably not the source of the problem: it appears we're running the test suite once for each of python 3.8, 3.9, 3.10 and 3.11, but those versions are only applied on the host platform. The tests still run in docker and the image is built on python:3.8-slim, so it we may actually be testing 3.8 four times. This is evidenced by the github action logs for the failing tests, which list the following prior to test runs on 3.10 and 3.11:

```
platform linux -- Python 3.8.18, pytest-7.4.3, pluggy-1.3.0 -- /usr/local/bin/python
```

**Comment by edkeeble** [comment]
@gadomski Looks like the issue is in a recent release of pytest-asyncio. There's a prerelease version (0.23.3) up to resolve the bug: https://pytest-asyncio.readthedocs.io/en/latest/reference/changelog.html#unreleased

**Review by gadomski — APPROVED** [review]

**Comment by gadomski** [comment]
Thanks for the PR and your patience, @edkeeble. Looks like the PyPI publish failed: https://github.com/stac-utils/stac-fastapi-pgstac/actions/runs/7188583458/job/19578503637. I haven't dug into it yet, but it _could_ be because the PyPI password has expired for the **stac-utils** org (just a guess)? I'll check tomorrow.

**Comment by gadomski** [comment]
Ok, we've got the permissions figured out, release published: https://pypi.org/project/stac-fastapi.pgstac/2.4.11/. Thanks for your patience @edkeeble!

**Pull request merged**
